export const CALCULATION_OBJECT = {
	medicalData: {
		gender: "",
		hiv: "",
		checkUp: "",
		medHistory: "",
		cancer: { state: "", level: 0 },
		hypertension: { state: "", level: 0 },
		cholesterol: { state: "", level: 0 },
		asthma: { state: "", level: 0 },
		diabetes: { state: "", level: "" },
		liver: { state: "", level: 0 },
		kidney: { state: "", level: 0 },
		apnea: { state: "", level: 0 },
		bipolar: { state: "", level: 0 },
		neuroDisorder: { state: "", level: 0 },
		psychiatric: { state: "", level: 0 },
		heartIssue: { state: "", level: 0 },
		angiography: { state: "", level: 0 },
		anxiety: { state: "", level: 0 },
	},
	lifeStyle: {
		gender: "",
		phyActive: "",
		phyActivities: "",
		fruitVeg: "",
		fruitvegportion: "",
		disabilities: "",
		tobacco: "",
		drugabuse: "",
		alchohol: "",
	},
	legalRisk: {
		gender: "",
		infractions: 0,
		criminal: "",
		duidwi: {
			state: "",
			level: 0,
		},
	},
	financialRisk: {
		bankcrupt: {
			state: "",
			level: 2,
		},
		creditrating: "",
	},
	insurance: {
		gender: "",
		lifeCoverage: "",
		decline: "",
	},
	personalInformation: {
		gender: "",
		date: "",
		firstName: "",
		lastName: "",
		paymentType: "",
		address: "",
		dateBirth: "",
		ageAuto: "",
		contact: "",
		SSN: "",
		email: "",
		height: "",
		weightLBS: "",
		weightBMI: "",
		insuranceCompanyRating: "",
		insuranceCompany: "",
	},
	paymentInfo: {
		startDate: "",
		endDate: "",
		calEndDateHedge: "",
		calEndDateUnhedge: "",
		paymentAmount: "",
		atPercent: "",
		paymentAmountAt100: "",
		paymentMode: "",
		annualIncrese: "",
	},
	moreDetails: {
		childSupport: { state: "", level: 0 },
		married: "",
	},
};
