module.exports = Object.freeze({
	medicalData: {
		gender: "female",
		hiv: "yes",
		checkUp: "no",
		medHistory: "yes",
		cancer: { state: "no", level: 5 },
		hypertension: { state: "Medicated", level: 5 },
		cholesterol: { state: "Medicated", level: 5 },
		asthma: { state: "yes", level: 5 },
		diabetes: { state: "yes", level: "type-1" },
		liver: { state: "yes", level: 5 },
		kidney: { state: "yes", level: 5 },
		apnea: { state: "yes", level: 5 },
		bipolar: { state: "yes", level: 5 },
		neuroDisorder: { state: "yes", level: 5 },
		psychiatric: { state: "yes", level: 5 },
		heartIssue: { state: "yes", level: 5 },
		angiography: { state: "yes", level: 5 },
		anxiety: { state: "yes", level: 5 },
	},
	lifeStyle: {
		gender: "female",
		phyActive: "yes",
		phyActivities: "once a week",
		fruitVeg: "yes",
		fruitvegportion: "no vegies",
		disabilities: "yes",
		tobacco: "no",
		drugabuse: "no",
		alchohol: "1-3 drinks daily",
	},
	legalRisk: {
		infractions: 3,
		gender: "female",
		criminal: "yes",
		duidwi: {
			state: "yes",
			level: 4,
		},
	},
	financialRisk: {
		gender: "female",
		bankcrupt: {
			state: "yes",
			level: 2,
		},
		creditrating: "Good 680-719",
	},
	insurance: {
		gender: "female",
		lifeCoverage: "yes",
		decline: "yes",
	},
});
